import type { JobListing } from "../types";

export const healthcareJobs: JobListing[] = [
  {
    id: "j001",
    title: "Registered Nurse - Med/Surg",
    company: "Jackson Hospital",
    source: "indeed",
    address: "1725 Pine Street, Montgomery, AL 36106",
    lat: 32.36561,
    lng: -86.29474,
    geocodeSource: "arcgis_business_license",
    jobType: "Full-time",
    salary: "$28.00 - $42.00/hr",
    seniority: "",
    industry: "Healthcare",
    posted: "2026-03-03",
    url: "",
    applyLink: "",
    skills: {
      healthcare: ["rn", "nursing", "patient care", "cpr"],
      education: ["bachelor", "licensed"],
      soft_skills: ["communication", "teamwork"],
      clearance: ["background check"],
    },
    skillSummary: "rn, nursing, patient care, cpr, bachelor, licensed, communication, teamwork, background check",
    benefits: ["Health insurance", "401k", "PTO"],
    scrapedAt: "2026-03-05T18:00:00Z",
  },
  {
    id: "j008",
    title: "CNA - Certified Nursing Assistant",
    company: "Baptist Health",
    source: "indeed",
    address: "Montgomery, AL 36116",
    lat: 32.33365,
    lng: -86.24790,
    geocodeSource: "nominatim",
    jobType: "Full-time",
    salary: "$13.50 - $17.00/hr",
    seniority: "Entry level",
    industry: "Healthcare",
    posted: "2026-03-05",
    url: "",
    applyLink: "",
    skills: {
      healthcare: ["cna", "patient care", "cpr", "first aid"],
      education: ["certification"],
      soft_skills: ["communication", "teamwork"],
      physical: ["lifting", "standing"],
      clearance: ["background check", "drug test"],
    },
    skillSummary: "cna, patient care, cpr, first aid, certification, communication, teamwork, lifting, standing, background check, drug test",
    benefits: ["Health insurance", "Tuition reimbursement"],
    scrapedAt: "2026-03-05T18:00:00Z",
  },
];
