import type { JobListing } from "../types";

export const manufacturingJobs: JobListing[] = [
  {
    id: "j003",
    title: "Production Operator",
    company: "Viscofan USA",
    source: "indeed",
    address: "3650 Industrial Park Drive, Montgomery, AL 36109",
    lat: 32.38126,
    lng: -86.36291,
    geocodeSource: "arcgis_business_license",
    jobType: "Full-time",
    salary: "$15.00 - $18.00/hr",
    seniority: "Entry level",
    industry: "Manufacturing",
    posted: "2026-03-02",
    url: "",
    applyLink: "",
    skills: {
      technical: ["mechanical", "forklift"],
      physical: ["lifting", "standing", "manual labor"],
      clearance: ["drug test", "background check"],
      experience: ["1 year"],
    },
    skillSummary: "mechanical, forklift, lifting, standing, manual labor, drug test, background check, 1 year",
    benefits: ["Health insurance"],
    scrapedAt: "2026-03-05T18:00:00Z",
  },
  {
    id: "j006",
    title: "HVAC Technician",
    company: "Dixie Electric",
    source: "indeed",
    address: "Montgomery, AL 36116",
    lat: 32.33365,
    lng: -86.24790,
    geocodeSource: "nominatim",
    jobType: "Full-time",
    salary: "$20.00 - $32.00/hr",
    seniority: "Mid-Senior",
    industry: "Skilled Trades",
    posted: "2026-03-01",
    url: "",
    applyLink: "",
    skills: {
      technical: ["hvac", "electrical"],
      education: ["certification"],
      experience: ["3 year"],
      physical: ["physical", "driving"],
      clearance: ["background check"],
    },
    skillSummary: "hvac, electrical, certification, 3 year, physical, driving, background check",
    benefits: ["Health insurance", "Company vehicle"],
    scrapedAt: "2026-03-05T18:00:00Z",
  },
  {
    id: "j007",
    title: "Maintenance Technician",
    company: "Dasmen Residential",
    source: "linkedin",
    address: "1000 Plantation Way, Montgomery, AL 36117",
    lat: 32.36280,
    lng: -86.17847,
    geocodeSource: "arcgis_business_license",
    jobType: "Full-time",
    salary: "$16.00 - $22.00/hr",
    seniority: "Entry level",
    industry: "Property Management",
    posted: "2026-03-04",
    url: "",
    applyLink: "",
    skills: {
      technical: ["plumbing", "electrical", "hvac"],
      physical: ["physical", "lifting"],
      experience: ["1 year"],
      clearance: ["background check"],
    },
    skillSummary: "plumbing, electrical, hvac, physical, lifting, 1 year, background check",
    benefits: ["Health insurance", "Free housing discount"],
    scrapedAt: "2026-03-05T18:00:00Z",
  },
];
