import type { JobListing } from "../types";

export const officeJobs: JobListing[] = [
  {
    id: "j005",
    title: "Customer Service Representative",
    company: "ALFA Insurance",
    source: "linkedin",
    address: "Montgomery, AL 36104",
    lat: 32.37771,
    lng: -86.30908,
    geocodeSource: "nominatim",
    jobType: "Full-time",
    salary: "$14.00 - $18.00/hr",
    seniority: "Entry level",
    industry: "Insurance",
    posted: "2026-03-03",
    url: "",
    applyLink: "",
    skills: {
      technical: ["microsoft office", "computer", "data entry"],
      soft_skills: ["customer service", "communication", "problem solving"],
      education: ["high school"],
    },
    skillSummary: "microsoft office, computer, data entry, customer service, communication, problem solving, high school",
    benefits: ["Health insurance", "401k", "PTO"],
    scrapedAt: "2026-03-05T18:00:00Z",
  },
  {
    id: "j009",
    title: "Data Entry Clerk",
    company: "State of Alabama",
    source: "linkedin",
    address: "Montgomery, AL 36130",
    lat: 32.37771,
    lng: -86.30908,
    geocodeSource: "nominatim",
    jobType: "Full-time",
    salary: "$12.50 - $15.00/hr",
    seniority: "Entry level",
    industry: "Government",
    posted: "2026-03-04",
    url: "",
    applyLink: "",
    skills: {
      technical: ["data entry", "microsoft office", "excel", "computer"],
      soft_skills: ["detail oriented", "organizational"],
      education: ["high school"],
    },
    skillSummary: "data entry, microsoft office, excel, computer, detail oriented, organizational, high school",
    benefits: ["State benefits", "Pension", "PTO"],
    scrapedAt: "2026-03-05T18:00:00Z",
  },
];
