import type { JobListing } from "../types";

export const retailJobs: JobListing[] = [
  {
    id: "j002",
    title: "Warehouse Associate",
    company: "Costco Wholesale",
    source: "indeed",
    address: "1500 Eastern Blvd, Montgomery, AL 36117",
    lat: 32.37168,
    lng: -86.22507,
    geocodeSource: "arcgis_business_license",
    jobType: "Full-time",
    salary: "$17.00 - $19.50/hr",
    seniority: "Entry level",
    industry: "Retail / Warehouse",
    posted: "2026-03-04",
    url: "",
    applyLink: "",
    skills: {
      physical: ["lifting", "warehouse", "standing"],
      soft_skills: ["teamwork", "customer service"],
      experience: ["no experience"],
    },
    skillSummary: "lifting, warehouse, standing, teamwork, customer service, no experience",
    benefits: ["Health insurance", "Dental", "Vision", "401k"],
    scrapedAt: "2026-03-05T18:00:00Z",
  },
  {
    id: "j010",
    title: "Fulfillment Supervisor",
    company: "Amazon",
    source: "indeed",
    address: "4000 North Park Drive, Montgomery, AL 36105",
    lat: 32.34974,
    lng: -86.33826,
    geocodeSource: "nominatim",
    jobType: "Full-time",
    salary: "$15.00 - $21.00/hr",
    seniority: "Mid-Senior",
    industry: "Logistics",
    posted: "2026-03-02",
    url: "",
    applyLink: "",
    skills: {
      soft_skills: ["leadership", "teamwork", "time management"],
      technical: ["forklift", "computer"],
      physical: ["warehouse", "lifting", "standing"],
      experience: ["2 year"],
    },
    skillSummary: "leadership, teamwork, time management, forklift, computer, warehouse, lifting, standing, 2 year",
    benefits: ["Health insurance", "401k", "Tuition"],
    scrapedAt: "2026-03-05T18:00:00Z",
  },
];
