import type { AppState, ServiceCategory, NewsCategory } from "../types";

export const initialState: AppState = {
  messages: [],
  language: "EN",
  activeView: "services",
  activeFlow: null,
  profile: {},
  artifacts: [],
  activeArtifactId: null,
  actionItems: [],
  isTyping: false,
  processingSteps: [],
  cvData: null,
  cvFileName: null,
  cvAnalyzing: false,
  selectedPin: null,
  activeCategories: ["health", "community", "childcare", "education", "safety", "libraries"] as ServiceCategory[],
  servicePoints: [],
  guideMessages: [],
  guideTyping: false,
  jobListings: [],
  jobMatches: [],
  trendingSkills: [],
  jobsLoading: false,
  upskillingSummary: null,
  transitRoutes: [],
  commuteEstimates: [],
  citizenMeta: null,
  newsArticles: [],
  newsLoading: false,
  newsCategory: "all" as NewsCategory,
  newsComments: [],
  likedArticleIds: [],
  selectedArticleId: null,
  newsMapVisible: false,
  newsMapMode: "pins" as const,
  newsReactions: {},
  userReactions: {},
  articleReactions: {},
  flaggedArticleIds: [],
  chatBubbleOpen: false,
  chatBubbleHasUnread: false,
  mapCommand: null,
  guidePendingMessage: null,
  housingListings: [],
  activeRoadmap: null,
  roadmapCompletedStepIds: [],
};
