/**
 * Mock job data based on real Bright Data scraping results from Montgomery, AL.
 * In production, this is replaced by live data from job_scraper_service.py webhook.
 */
import type { JobListing } from "./types";

export const MOCK_JOB_LISTINGS: JobListing[] = [
  {
    id: "j001",
    title: "Registered Nurse - Med/Surg",
    company: "Jackson Hospital",
    source: "indeed",
    address: "1725 Pine Street, Montgomery, AL 36106",
    lat: 32.36561,
    lng: -86.29474,
    geocodeSource: "arcgis_business_license",
    jobType: "Full-time",
    salary: "$28.00 - $42.00/hr",
    seniority: "",
    industry: "Healthcare",
    posted: "2026-03-03",
    url: "",
    applyLink: "",
    skills: {
      healthcare: ["rn", "nursing", "patient care", "cpr"],
      education: ["bachelor", "licensed"],
      soft_skills: ["communication", "teamwork"],
      clearance: ["background check"],
    },
    skillSummary: "rn, nursing, patient care, cpr, bachelor, licensed, communication, teamwork, background check",
    benefits: ["Health insurance", "401k", "PTO"],
    scrapedAt: "2026-03-05T18:00:00Z",
  },
  {
    id: "j002",
    title: "Warehouse Associate",
    company: "Costco Wholesale",
    source: "indeed",
    address: "1500 Eastern Blvd, Montgomery, AL 36117",
    lat: 32.37168,
    lng: -86.22507,
    geocodeSource: "arcgis_business_license",
    jobType: "Full-time",
    salary: "$17.00 - $19.50/hr",
    seniority: "Entry level",
    industry: "Retail / Warehouse",
    posted: "2026-03-04",
    url: "",
    applyLink: "",
    skills: {
      physical: ["lifting", "warehouse", "standing"],
      soft_skills: ["teamwork", "customer service"],
      experience: ["no experience"],
    },
    skillSummary: "lifting, warehouse, standing, teamwork, customer service, no experience",
    benefits: ["Health insurance", "Dental", "Vision", "401k"],
    scrapedAt: "2026-03-05T18:00:00Z",
  },
  {
    id: "j003",
    title: "Production Operator",
    company: "Viscofan USA",
    source: "indeed",
    address: "3650 Industrial Park Drive, Montgomery, AL 36109",
    lat: 32.38126,
    lng: -86.36291,
    geocodeSource: "arcgis_business_license",
    jobType: "Full-time",
    salary: "$15.00 - $18.00/hr",
    seniority: "Entry level",
    industry: "Manufacturing",
    posted: "2026-03-02",
    url: "",
    applyLink: "",
    skills: {
      technical: ["mechanical", "forklift"],
      physical: ["lifting", "standing", "manual labor"],
      clearance: ["drug test", "background check"],
      experience: ["1 year"],
    },
    skillSummary: "mechanical, forklift, lifting, standing, manual labor, drug test, background check, 1 year",
    benefits: ["Health insurance"],
    scrapedAt: "2026-03-05T18:00:00Z",
  },
  {
    id: "j004",
    title: "CDL Truck Driver",
    company: "Montgomery Transport",
    source: "indeed",
    address: "Montgomery, AL 36104",
    lat: 32.37771,
    lng: -86.30908,
    geocodeSource: "nominatim",
    jobType: "Full-time",
    salary: "$22.00 - $28.00/hr",
    seniority: "Mid-Senior",
    industry: "Transportation",
    posted: "2026-03-04",
    url: "",
    applyLink: "",
    skills: {
      technical: ["cdl"],
      physical: ["driving", "lifting"],
      clearance: ["drug test", "background check"],
      experience: ["2 year"],
    },
    skillSummary: "cdl, driving, lifting, drug test, background check, 2 year",
    benefits: ["Health insurance", "PTO"],
    scrapedAt: "2026-03-05T18:00:00Z",
  },
  {
    id: "j005",
    title: "Customer Service Representative",
    company: "ALFA Insurance",
    source: "linkedin",
    address: "Montgomery, AL 36104",
    lat: 32.37771,
    lng: -86.30908,
    geocodeSource: "nominatim",
    jobType: "Full-time",
    salary: "$14.00 - $18.00/hr",
    seniority: "Entry level",
    industry: "Insurance",
    posted: "2026-03-03",
    url: "",
    applyLink: "",
    skills: {
      technical: ["microsoft office", "computer", "data entry"],
      soft_skills: ["customer service", "communication", "problem solving"],
      education: ["high school"],
    },
    skillSummary: "microsoft office, computer, data entry, customer service, communication, problem solving, high school",
    benefits: ["Health insurance", "401k", "PTO"],
    scrapedAt: "2026-03-05T18:00:00Z",
  },
  {
    id: "j006",
    title: "HVAC Technician",
    company: "Dixie Electric",
    source: "indeed",
    address: "Montgomery, AL 36116",
    lat: 32.33365,
    lng: -86.24790,
    geocodeSource: "nominatim",
    jobType: "Full-time",
    salary: "$20.00 - $32.00/hr",
    seniority: "Mid-Senior",
    industry: "Skilled Trades",
    posted: "2026-03-01",
    url: "",
    applyLink: "",
    skills: {
      technical: ["hvac", "electrical"],
      education: ["certification"],
      experience: ["3 year"],
      physical: ["physical", "driving"],
      clearance: ["background check"],
    },
    skillSummary: "hvac, electrical, certification, 3 year, physical, driving, background check",
    benefits: ["Health insurance", "Company vehicle"],
    scrapedAt: "2026-03-05T18:00:00Z",
  },
  {
    id: "j007",
    title: "Maintenance Technician",
    company: "Dasmen Residential",
    source: "linkedin",
    address: "1000 Plantation Way, Montgomery, AL 36117",
    lat: 32.36280,
    lng: -86.17847,
    geocodeSource: "arcgis_business_license",
    jobType: "Full-time",
    salary: "$16.00 - $22.00/hr",
    seniority: "Entry level",
    industry: "Property Management",
    posted: "2026-03-04",
    url: "",
    applyLink: "",
    skills: {
      technical: ["plumbing", "electrical", "hvac"],
      physical: ["physical", "lifting"],
      experience: ["1 year"],
      clearance: ["background check"],
    },
    skillSummary: "plumbing, electrical, hvac, physical, lifting, 1 year, background check",
    benefits: ["Health insurance", "Free housing discount"],
    scrapedAt: "2026-03-05T18:00:00Z",
  },
  {
    id: "j008",
    title: "CNA - Certified Nursing Assistant",
    company: "Baptist Health",
    source: "indeed",
    address: "Montgomery, AL 36116",
    lat: 32.33365,
    lng: -86.24790,
    geocodeSource: "nominatim",
    jobType: "Full-time",
    salary: "$13.50 - $17.00/hr",
    seniority: "Entry level",
    industry: "Healthcare",
    posted: "2026-03-05",
    url: "",
    applyLink: "",
    skills: {
      healthcare: ["cna", "patient care", "cpr", "first aid"],
      education: ["certification"],
      soft_skills: ["communication", "teamwork"],
      physical: ["lifting", "standing"],
      clearance: ["background check", "drug test"],
    },
    skillSummary: "cna, patient care, cpr, first aid, certification, communication, teamwork, lifting, standing, background check, drug test",
    benefits: ["Health insurance", "Tuition reimbursement"],
    scrapedAt: "2026-03-05T18:00:00Z",
  },
  {
    id: "j009",
    title: "Data Entry Clerk",
    company: "State of Alabama",
    source: "linkedin",
    address: "Montgomery, AL 36130",
    lat: 32.37771,
    lng: -86.30908,
    geocodeSource: "nominatim",
    jobType: "Full-time",
    salary: "$12.50 - $15.00/hr",
    seniority: "Entry level",
    industry: "Government",
    posted: "2026-03-04",
    url: "",
    applyLink: "",
    skills: {
      technical: ["data entry", "microsoft office", "excel", "computer"],
      soft_skills: ["detail oriented", "organizational"],
      education: ["high school"],
    },
    skillSummary: "data entry, microsoft office, excel, computer, detail oriented, organizational, high school",
    benefits: ["State benefits", "Pension", "PTO"],
    scrapedAt: "2026-03-05T18:00:00Z",
  },
  {
    id: "j010",
    title: "Fulfillment Supervisor",
    company: "Amazon",
    source: "indeed",
    address: "4000 North Park Drive, Montgomery, AL 36105",
    lat: 32.34974,
    lng: -86.33826,
    geocodeSource: "nominatim",
    jobType: "Full-time",
    salary: "$15.00 - $21.00/hr",
    seniority: "Mid-Senior",
    industry: "Logistics",
    posted: "2026-03-02",
    url: "",
    applyLink: "",
    skills: {
      soft_skills: ["leadership", "teamwork", "time management"],
      technical: ["forklift", "computer"],
      physical: ["warehouse", "lifting", "standing"],
      experience: ["2 year"],
    },
    skillSummary: "leadership, teamwork, time management, forklift, computer, warehouse, lifting, standing, 2 year",
    benefits: ["Health insurance", "401k", "Tuition"],
    scrapedAt: "2026-03-05T18:00:00Z",
  },
];
